import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";
import Link from "next/link";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <div className="drawer drawer-open">
          <input id="my-drawer-4" type="checkbox" className="drawer-toggle" />
          <div className="drawer-content p-4">
            <div className="flex flex-col gap-4">{children}</div>
          </div>

          <div className="drawer-side is-drawer-close:overflow-visible">
            <label
              htmlFor="my-drawer-4"
              aria-label="close sidebar"
              className="drawer-overlay"
            ></label>
            <div className="is-drawer-close:w-14 is-drawer-open:w-64 bg-base-200 flex flex-col items-start min-h-full">
              {/* Sidebar content here */}
              <ul className="menu w-full grow">
                {/* list item */}
                <li>
                  <Link
                    href="/port-scan"
                    className="is-drawer-close:tooltip is-drawer-close:tooltip-right"
                    data-tip="Port Scan"
                  >
                    <i className="inline-block size-4 my-1.5 nf nf-md-serial_port"></i>
                    <span className="is-drawer-close:hidden">Port Scan</span>
                  </Link>
                </li>

                {/* list item */}
                <li>
                  <Link
                    href="/fuzzing"
                    className="is-drawer-close:tooltip is-drawer-close:tooltip-right"
                    data-tip="Fuzzing"
                  >
                    <i className="inline-block size-4 my-1.5 nf nf-cod-search_fuzzy"></i>
                    <span className="is-drawer-close:hidden">Fuzzing</span>
                  </Link>
                </li>
              </ul>

              {/* button to open/close drawer */}
              <div
                className="m-2 is-drawer-close:tooltip is-drawer-close:tooltip-right"
                data-tip="Open"
              >
                <label
                  htmlFor="my-drawer-4"
                  className="btn btn-ghost btn-circle drawer-button is-drawer-open:rotate-y-180"
                >
                  <svg
                    xmlns="http://www.w3.org/2000/svg"
                    viewBox="0 0 24 24"
                    strokeLinejoin="round"
                    strokeLinecap="round"
                    strokeWidth="2"
                    fill="none"
                    stroke="currentColor"
                    className="inline-block size-4 my-1.5"
                  >
                    <path d="M4 4m0 2a2 2 0 0 1 2 -2h12a2 2 0 0 1 2 2v12a2 2 0 0 1 -2 2h-12a2 2 0 0 1 -2 -2z"></path>
                    <path d="M9 4v16"></path>
                    <path d="M14 10l2 2l-2 2"></path>
                  </svg>
                </label>
              </div>
            </div>
          </div>
        </div>
      </body>
    </html>
  );
}
